transform:
  type: environmental
  environment:
    - x1
    - x2
    - a1
    - a2
    - b1
    - b2
  performance: performance
  y_column: level
source:
  type: local
  files:
    - s10: ../../data/xdpole/initialconditions/s10_run.csv
