transform:
  type: environmental
  environment:
    - x1
    - x2
    - a1
    - a2
    - b1
    - b2
  performance: performance
  y_column: level
source:
  type: local
  files:
    # - ../../data/xdpole/initialconditions/s1_run.csv
    # - ../../data/xdpole/initialconditions/s2_run.csv
    # - ../../data/xdpole/initialconditions/s3_run.csv
    # - ../../data/xdpole/initialconditions/s4_run.csv 
    # - ../../data/xdpole/initialconditions/s5_run.csv
    # - ../../data/xdpole/initialconditions/s6_run.csv
    # - ../../data/xdpole/initialconditions/s7_run.csv
    # - ../../data/xdpole/initialconditions/s8_run.csv
    # - ../../data/xdpole/initialconditions/s9_run.csv
    - ../../data/xdpole/initialconditions/s10_run.csv
